import os
import sqlite3
import json

def setup_directories():
    directories = [
        "mock_data",
        "mock_data/docs",
        "mock_data/docs/design_decisions",
        "mock_data/docs/pipelines",
        "mock_data/codebase",
        "mock_data/codebase/dbt/models/staging",
        "mock_data/codebase/dbt/models/marts",
        "mock_data/codebase/airflow/dags",
        "mock_data/logs"
    ]
    for directory in directories:
        os.makedirs(directory, exist_ok=True)
    print("Created mock directories.")

def setup_docs():
    # 1. Architecture overview
    architecture_overview = """# Data Platform Architecture Overview

Welcome to the enterprise Data Platform documentation! This project follows a modern Lakehouse architecture based on the **Medallion design pattern** (Bronze -> Silver -> Gold) hosted on AWS and Snowflake.

## Architectural Layers

```
  [Raw Sources]
        |  (Airflow + custom ingestion python scripts)
        v
+-----------------+
|   Bronze Lake   |  Raw database replication, JSON API outputs, S3 logs.
| (raw_schema)    |  * Append-only ingestion, partitioned by day.
+--------+--------+
         |  (dbt staging transformations)
         v
+-----------------+
|  Silver Lake    |  Cleaned, conformed, hashed PII, schema validated.
| (staging_schema)|  * Filtered records, default conversions, data type standardizations.
+--------+--------+
         |  (dbt marts transformations)
         v
+-----------------+
|   Gold Lake     |  Business-level aggregates, star schema, denormalized dimensions.
|  (marts_schema) |  * Highly optimized for BI (Looker, Tableau) and ML modeling.
+-----------------+
```

## Primary Storage & Transformation Tech Stack
* **Storage & Compute**: Snowflake acts as the primary data warehouse (Lakehouse compute).
* **Ingestion**: Custom Python scripts orchestrated by Apache Airflow load data from PostgreSQL RDS, external APIs, and S3 buckets into Snowflake's `Bronze` schema.
* **Transformations**: dbt (data build tool) is utilized to manage dependencies and build view/table layers across `Silver` (Staging) and `Gold` (Marts).
* **Metadata & Lineage**: Handled via table tags in Snowflake and dbt documentation manifests.
"""
    
    # 2. Design decisions - PII governance
    pii_governance = """# Architectural Decision Record (ADR): PII Data Masking & Governance

* **Status**: Approved
* **Date**: October 14, 2025
* **Author**: Lead Data Architect

## Context
Under compliance policies (GDPR and CCPA), Personally Identifiable Information (PII) must not be accessible in downstream business-level aggregates (`Gold` layer) or queryable by analyst roles without explicitly approved security clearance. 

## Decisions
1. **Source Isolation**: All raw tables in the `Bronze` schema containing PII (e.g. email, phone numbers, customer names) are locked down and restricted exclusively to the `airflow_svc` ingestion role.
2. **Silver-Layer Masking**: As data transitions from `Bronze` (raw) to `Silver` (staging), PII columns MUST be transformed using SHA-256 hashing with a system salt, or fully masked.
   * Email fields: Standardized to lowercase and hashed using `SHA2(email || salt)`.
   * Phone numbers: Masked to keep only the country code and last 4 digits (e.g. `+1-XXX-XXX-4821`).
   * Names: Replaced with synthetic surrogate tokens generated by hashing user IDs.
3. **Audit Trail**: Metadata properties must explicitly tag columns containing PII with `is_pii = true` and details of their masking policy.
"""

    # 3. Design decisions - Orchestration choices
    orchestration_choices = """# Architectural Decision Record (ADR): Airflow for Orchestration & dbt for ELT

* **Status**: Approved
* **Date**: July 22, 2025
* **Author**: Platform Team

## Context
We need a robust, scalable workflow orchestrator capable of managing external API ingestion, heavy DB extraction, and modeling workflows.

## Decisions
1. **Decoupled Orchestration vs. Transformation**:
   * **Apache Airflow** is chosen to orchestrate *ingestion* tasks (extracting from PostgreSQL RDS, pulling third-party API data, dumping to S3, loading to Snowflake Bronze).
   * **dbt** is chosen for all internal Snowflake *transformations* (Silver staging and Gold marts).
2. **Orchestration Pattern**:
   * Airflow triggers the dbt jobs using the `dbt-cloud` CLI / API interface or locally inside ECS tasks, ensuring that dbt models run only after their respective Bronze source ingestion pipelines complete successfully.
   * Airflow monitors execution status, handles alerting to Slack/PagerDuty, and manages job retries.
"""

    # 4. Pipeline doc - User Analytics Pipeline
    user_analytics_pipeline = """# Customer Analytics & Chern Pipeline Documentation

## Overview
The Customer Analytics and Churn Pipeline is a vital data model that compiles daily activity patterns, transaction frequencies, and demographic metadata to calculate customer retention metrics and predict churn probability.

## Pipeline Flow
1. **Ingestion (Airflow)**: Extract daily postgres updates for customer profiles and transactional events. Load them into Snowflake `raw_users` and `raw_transactions`.
2. **Staging & Cleaning (dbt)**:
   * `stg_users`: Cleans name strings, enforces uniform timestamps, hashes raw emails.
   * `stg_transactions`: Verifies payment processor keys, casts floats, filters failed tests.
3. **Marts Aggregations (dbt)**:
   * `fct_user_transactions`: Aggregates transactions by user and day.
   * `fct_user_churn`: Joins transaction activity with user profiles to flags users as "inactive" or "active" based on a rolling 30-day window.

## SLO & Data SLA Targets
* **SLA Time**: Data must be completely refreshed and validated in `marts.fct_user_churn` daily by **08:00 UTC**.
* **Failure Actions**: If the Airflow orchestrator fails or dbt validations fail, a Slack alert is triggered, and downstream BI reports are flagged with a "Stale Data" warning.
"""

    # Write files
    with open("mock_data/docs/architecture_overview.md", "w") as f:
        f.write(architecture_overview)
    with open("mock_data/docs/design_decisions/pii_governance.md", "w") as f:
        f.write(pii_governance)
    with open("mock_data/docs/design_decisions/orchestration_choices.md", "w") as f:
        f.write(orchestration_choices)
    with open("mock_data/docs/pipelines/customer_churn_pipeline.md", "w") as f:
        f.write(user_analytics_pipeline)
        
    print("Created mock markdown docs.")

def setup_codebase():
    # 1. dbt staging: stg_users.sql
    stg_users_sql = """-- stg_users.sql
-- Cleans and hashes raw user profile information from bronze.raw_users.
-- Implements SHA-256 hashing for compliance with ADR PII standards.

WITH raw_source AS (
    SELECT
        id AS user_id,
        first_name,
        last_name,
        email,
        phone_number,
        country_code,
        created_at,
        updated_at
    FROM {{ source('bronze', 'raw_users') }}
)

SELECT
    user_id,
    -- Hashing PII for GDPR compliance (ADR-002)
    SHA2(LOWER(email) || 'f8c3d9b1e5a26748c9d0e1f2b3a4c5d6') AS hashed_email,
    -- Masking phone number (keeps country code and last 4 digits)
    CONCAT('+', country_code, '-XXX-XXX-', RIGHT(phone_number, 4)) AS masked_phone,
    UPPER(country_code) AS country,
    CAST(created_at AS TIMESTAMP) AS created_timestamp,
    CAST(updated_at AS TIMESTAMP) AS updated_timestamp
FROM raw_source
"""

    # 2. dbt staging: stg_transactions.sql
    stg_transactions_sql = """-- stg_transactions.sql
-- Cleans transaction records from bronze.raw_transactions.
-- Casts price values, extracts calendar attributes, and filters test payments.

WITH raw_source AS (
    SELECT
        transaction_id,
        user_id,
        amount_usd,
        status,
        payment_method,
        transaction_time
    FROM {{ source('bronze', 'raw_transactions') }}
)

SELECT
    transaction_id,
    user_id,
    CAST(amount_usd AS DECIMAL(18, 2)) AS transaction_amount_usd,
    LOWER(status) AS transaction_status,
    payment_method,
    CAST(transaction_time AS TIMESTAMP) AS transaction_timestamp
FROM raw_source
WHERE LOWER(status) != 'test_payment'
"""

    # 3. dbt marts: fct_user_transactions.sql
    fct_user_transactions_sql = """-- fct_user_transactions.sql
-- Aggregates daily transaction statistics per user.
-- Depends on stg_transactions.

WITH transactions AS (
    SELECT
        user_id,
        transaction_amount_usd,
        transaction_timestamp
    FROM {{ ref('stg_transactions') }}
    WHERE transaction_status = 'completed'
)

SELECT
    user_id,
    COUNT(transaction_amount_usd) AS lifetime_transaction_count,
    SUM(transaction_amount_usd) AS lifetime_spend_usd,
    MAX(transaction_timestamp) AS last_active_timestamp
FROM transactions
GROUP BY user_id
"""

    # 4. dbt marts: fct_user_churn.sql
    fct_user_churn_sql = """-- fct_user_churn.sql
-- Defines customer status: active vs. inactive (churned).
-- Joins cleaned user metadata with transaction histories.
-- Must enforce unique constraint on user_id.

WITH users AS (
    SELECT
        user_id,
        hashed_email,
        country
    FROM {{ ref('stg_users') }}
),

activity AS (
    SELECT
        user_id,
        lifetime_transaction_count,
        lifetime_spend_usd,
        last_active_timestamp
    FROM {{ ref('fct_user_transactions') }}
)

SELECT
    u.user_id,
    u.hashed_email,
    u.country,
    COALESCE(a.lifetime_transaction_count, 0) AS tx_count,
    COALESCE(a.lifetime_spend_usd, 0.0) AS spend_amount,
    a.last_active_timestamp,
    CASE 
        -- Flag as churned if no transaction in past 30 days
        WHEN a.last_active_timestamp IS NULL THEN 'CHURNED'
        WHEN DATEDIFF('day', a.last_active_timestamp, CURRENT_DATE()) > 30 THEN 'CHURNED'
        ELSE 'ACTIVE'
    END AS churn_status
FROM users u
LEFT JOIN activity a ON u.user_id = a.user_id
"""

    # 5. Airflow DAG: user_analytics_dag.py
    airflow_dag_py = """# user_analytics_dag.py
# Ingests user profiles and event data, then runs dbt transformation pipeline.

from datetime import datetime, timedelta
from airflow import DAG
from airflow.operators.python import PythonOperator
from airflow.providers.snowflake.operators.snowflake import SnowflakeOperator
from airflow.operators.bash import BashOperator

default_args = {
    'owner': 'data_engineering',
    'depends_on_past': False,
    'email': ['de-alerts@company.com'],
    'email_on_failure': True,
    'retries': 2,
    'retry_delay': timedelta(minutes=5)
}

def extract_users_from_rds():
    # Extracts fresh accounts from transaction database RDS
    # Custom ETL code logic
    print("Starting ingestion: Connecting to db.production.local ...")
    # Simulate DB fetching
    print("Ingested 14,812 rows. Writing to S3 bronze bucket...")

def extract_transactions_from_stripe():
    # Ingests transaction events from Stripe external API
    print("Querying Stripe endpoints...")
    print("Ingested 4,921 Stripe rows. Copying into S3 bronze...")

with DAG(
    'user_analytics_pipeline',
    default_args=default_args,
    description='Nightly ingestion and dbt marts rebuild pipeline for Customer Churn models',
    schedule_interval='0 2 * * *',  # Daily at 2:00 AM UTC
    start_date=datetime(2025, 1, 1),
    catchup=False,
    tags=['churn', 'users', 'stripe']
) as dag:

    ingest_users = PythonOperator(
        task_id='extract_users_from_rds',
        python_callable=extract_users_from_rds
    )

    ingest_transactions = PythonOperator(
        task_id='extract_transactions_from_stripe',
        python_callable=extract_transactions_from_stripe
    )

    snowflake_load_raw = SnowflakeOperator(
        task_id='load_s3_to_snowflake_bronze',
        snowflake_conn_id='snowflake_prod',
        sql="COPY INTO bronze.raw_users FROM @s3_bronze_stage/users/;"
    )

    dbt_run = BashOperator(
        task_id='dbt_run_transformations',
        bash_command='dbt run --profiles-dir . --project-dir ./dbt'
    )

    dbt_test = BashOperator(
        task_id='dbt_test_validations',
        bash_command='dbt test --profiles-dir . --project-dir ./dbt'
    )

    # Dependency routing
    [ingest_users, ingest_transactions] >> snowflake_load_raw >> dbt_run >> dbt_test
"""

    with open("mock_data/codebase/dbt/models/staging/stg_users.sql", "w") as f:
        f.write(stg_users_sql)
    with open("mock_data/codebase/dbt/models/staging/stg_transactions.sql", "w") as f:
        f.write(stg_transactions_sql)
    with open("mock_data/codebase/dbt/models/marts/fct_user_transactions.sql", "w") as f:
        f.write(fct_user_transactions_sql)
    with open("mock_data/codebase/dbt/models/marts/fct_user_churn.sql", "w") as f:
        f.write(fct_user_churn_sql)
    with open("mock_data/codebase/airflow/dags/user_analytics_dag.py", "w") as f:
        f.write(airflow_dag_py)
        
    print("Created mock codebase files (dbt + Airflow).")

def setup_logs():
    success_log = """2026-05-31T02:00:00Z [INFO] Starting Airflow Task Instance: customer_churn_dag.extract_users_from_rds
2026-05-31T02:00:01Z [INFO] Connecting to database host: db.production.local, port: 5432, database: prod_rds
2026-05-31T02:00:03Z [INFO] Extract query executed. Fetched 14,812 rows.
2026-05-31T02:00:04Z [INFO] Uploaded csv file to s3://company-datalake-bronze/users/date=2026-05-31/data.csv
2026-05-31T02:00:05Z [INFO] Task extract_users_from_rds finished. Status: SUCCESS
2026-05-31T02:00:05Z [INFO] Starting Airflow Task Instance: customer_churn_dag.load_s3_to_snowflake_bronze
2026-05-31T02:00:06Z [INFO] Executing COPY INTO bronze.raw_users in Snowflake warehouse PROD_WH...
2026-05-31T02:00:09Z [INFO] Snowflake COPY completed. 14,812 rows inserted.
2026-05-31T02:00:10Z [INFO] Starting Airflow Task Instance: customer_churn_dag.dbt_run_transformations
2026-05-31T02:00:11Z [INFO] Concurrency: 4 threads
2026-05-31T02:00:12Z [INFO] 1 of 4 START staging.stg_users ......................... [RUN]
2026-05-31T02:00:13Z [INFO] 2 of 4 START staging.stg_transactions .................. [RUN]
2026-05-31T02:00:15Z [INFO] 1 of 4 PASS staging.stg_users .......................... [OK in 2.92s]
2026-05-31T02:00:16Z [INFO] 2 of 4 PASS staging.stg_transactions ................... [OK in 3.12s]
2026-05-31T02:00:17Z [INFO] 3 of 4 START marts.fct_user_transactions ............... [RUN]
2026-05-31T02:00:19Z [INFO] 3 of 4 PASS marts.fct_user_transactions ................ [OK in 2.05s]
2026-05-31T02:00:20Z [INFO] 4 of 4 START marts.fct_user_churn ...................... [RUN]
2026-05-31T02:00:22Z [INFO] 4 of 4 PASS marts.fct_user_churn ....................... [OK in 1.95s]
2026-05-31T02:00:23Z [INFO] Done. PASS=4 WARN=0 ERROR=0 SKIP=0
2026-05-31T02:00:24Z [INFO] Starting Airflow Task Instance: customer_churn_dag.dbt_test_validations
2026-05-31T02:00:25Z [INFO] Running test unique_stg_users_user_id... [PASS]
2026-05-31T02:00:26Z [INFO] Running test not_null_stg_users_user_id... [PASS]
2026-05-31T02:00:27Z [INFO] Running test unique_fct_user_churn_user_id... [PASS]
2026-05-31T02:00:28Z [INFO] Running test relationships_fct_user_churn_user_id_stg_users_user_id... [PASS]
2026-05-31T02:00:29Z [INFO] All 4 tests passed. dbt run validated successfully!
2026-05-31T02:00:30Z [INFO] DAG user_analytics_pipeline completed. Status: SUCCESS
"""

    failed_dbt_log = """2026-05-31T04:15:00Z [INFO] Starting Airflow Task Instance: customer_churn_dag.dbt_run_transformations
2026-05-31T04:15:02Z [INFO] Concurrency: 4 threads
2026-05-31T04:15:03Z [INFO] 1 of 4 START staging.stg_users ......................... [RUN]
2026-05-31T04:15:04Z [INFO] 2 of 4 START staging.stg_transactions .................. [RUN]
2026-05-31T04:15:06Z [INFO] 1 of 4 PASS staging.stg_users .......................... [OK in 2.12s]
2026-05-31T04:15:07Z [INFO] 2 of 4 PASS staging.stg_transactions ................... [OK in 3.41s]
2026-05-31T04:15:08Z [INFO] 3 of 4 START marts.fct_user_transactions ............... [RUN]
2026-05-31T04:15:10Z [INFO] 3 of 4 PASS marts.fct_user_transactions ................ [OK in 2.11s]
2026-05-31T04:15:11Z [INFO] 4 of 4 START marts.fct_user_churn ...................... [RUN]
2026-05-31T04:15:13Z [ERROR] Database error: Duplicate entry 'USR_94821' for key 'fct_user_churn.primary'
2026-05-31T04:15:13Z [ERROR] 4 of 4 ERROR marts.fct_user_churn ..................... [ERROR in 1.87s]
2026-05-31T04:15:14Z [INFO] Done. PASS=3 WARN=0 ERROR=1 SKIP=0
2026-05-31T04:15:14Z [FATAL] Pipeline run failed due to compilation or execution error: Marts unique key violation.
Traceback (most recent call last):
  File "/opt/airflow/dags/customer_churn_dag.py", line 87, in trigger_dbt_run
    raise Exception("dbt transformations failed: Marts unique key violation inside marts.fct_user_churn")
Exception: dbt transformations failed: Marts unique key violation inside marts.fct_user_churn
"""

    failed_rds_log = """2026-05-31T02:00:00Z [INFO] Starting Airflow Task Instance: customer_churn_dag.extract_users_from_rds
2026-05-31T02:00:01Z [INFO] Connecting to database host: db.production.local, port: 5432, database: prod_rds
2026-05-31T02:00:16Z [WARNING] Retrying database connection (attempt 1/3)...
2026-05-31T02:00:31Z [WARNING] Retrying database connection (attempt 2/3)...
2026-05-31T02:00:46Z [WARNING] Retrying database connection (attempt 3/3)...
2026-05-31T02:01:01Z [ERROR] Failed to establish connection after 3 attempts.
Traceback (most recent call last):
  File "/opt/airflow/dags/customer_churn_dag.py", line 47, in extract_users_from_rds
    conn = psycopg2.connect(host="db.production.local", user="airflow_svc", password="***")
  File "/usr/local/lib/python3.10/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, async_=async_)
psycopg2.OperationalError: connection to server at "db.production.local" (10.0.4.12), port 5432 failed: Connection timed out
	Is the server running on that host and accepting TCP/IP connections?
2026-05-31T02:01:02Z [FATAL] Task failed. Exiting with error code 1.
"""

    with open("mock_data/logs/run_1001_success.log", "w") as f:
        f.write(success_log)
    with open("mock_data/logs/run_1002_failed.log", "w") as f:
        f.write(failed_dbt_log)
    with open("mock_data/logs/run_1003_failed.log", "w") as f:
        f.write(failed_rds_log)
        
    print("Created mock log files.")

def setup_sqlite():
    db_path = "mock_data/metadata.db"
    
    # Remove existing db if any
    if os.path.exists(db_path):
        os.remove(db_path)
        
    conn = sqlite3.connect(db_path)
    cursor = conn.cursor()

    # 1. Create tables table
    cursor.execute("""
    CREATE TABLE IF NOT EXISTS tables (
        table_id TEXT PRIMARY KEY,
        schema_name TEXT NOT NULL,
        table_name TEXT NOT NULL,
        description TEXT,
        row_count INTEGER,
        size_bytes INTEGER
    )
    """)

    # 2. Create columns table
    cursor.execute("""
    CREATE TABLE IF NOT EXISTS columns (
        table_id TEXT NOT NULL,
        column_name TEXT NOT NULL,
        data_type TEXT NOT NULL,
        description TEXT,
        is_pii BOOLEAN NOT NULL CHECK (is_pii IN (0, 1)),
        pii_type TEXT,
        masking_policy TEXT,
        PRIMARY KEY (table_id, column_name),
        FOREIGN KEY (table_id) REFERENCES tables(table_id)
    )
    """)

    # 3. Create lineage table
    cursor.execute("""
    CREATE TABLE IF NOT EXISTS lineage (
        source_table TEXT NOT NULL,
        target_table TEXT NOT NULL,
        lineage_type TEXT NOT NULL,
        PRIMARY KEY (source_table, target_table)
    )
    """)

    # 4. Create pipeline_runs table
    cursor.execute("""
    CREATE TABLE IF NOT EXISTS pipeline_runs (
        run_id INTEGER PRIMARY KEY AUTOINCREMENT,
        pipeline_name TEXT NOT NULL,
        status TEXT NOT NULL CHECK (status IN ('SUCCESS', 'FAILED')),
        start_time TEXT NOT NULL,
        end_time TEXT,
        duration_sec INTEGER,
        error_message TEXT,
        log_path TEXT
    )
    """)

    # 5. Create pipeline_slo table
    cursor.execute("""
    CREATE TABLE IF NOT EXISTS pipeline_slo (
        pipeline_name TEXT PRIMARY KEY,
        sla_target_time TEXT NOT NULL,
        max_duration_sec INTEGER NOT NULL,
        slo_percentage_target REAL NOT NULL
    )
    """)

    # ------------------ SEEDING DATA ------------------

    # Seeding Tables
    tables = [
        ("bronze.raw_users", "bronze", "raw_users", "Raw ingestion replica of postgres customer registrations database.", 153821, 24192081),
        ("bronze.raw_transactions", "bronze", "raw_transactions", "Raw transactions dump from Stripe API payments integration.", 952048, 142093848),
        ("staging.stg_users", "staging", "stg_users", "Cleaned user demographics and profiles. Hashes primary email fields.", 153812, 19283011),
        ("staging.stg_transactions", "staging", "stg_transactions", "Standardized currency conversions and transaction attributes. Ignores payments marked as test.", 948201, 98203810),
        ("marts.fct_user_transactions", "marts", "fct_user_transactions", "Fact table containing rolling aggregate metrics on user transaction activities.", 120482, 12038410),
        ("marts.fct_user_churn", "marts", "fct_user_churn", "Analyzes user activity to flag inactive accounts exceeding 30 days as churned. Primary reporting table.", 120482, 14028310)
    ]
    cursor.executemany("INSERT INTO tables VALUES (?, ?, ?, ?, ?, ?)", tables)

    # Seeding Columns
    columns = [
        # bronze.raw_users
        ("bronze.raw_users", "id", "TEXT", "Primary identifier for users.", 0, "NONE", None),
        ("bronze.raw_users", "first_name", "TEXT", "First name of customer.", 1, "NAME", "Raw (Restricted Access)"),
        ("bronze.raw_users", "last_name", "TEXT", "Last name of customer.", 1, "NAME", "Raw (Restricted Access)"),
        ("bronze.raw_users", "email", "TEXT", "Primary email address of user.", 1, "EMAIL", "Raw (Restricted Access)"),
        ("bronze.raw_users", "phone_number", "TEXT", "User phone number.", 1, "PHONE", "Raw (Restricted Access)"),
        ("bronze.raw_users", "country_code", "TEXT", "ISO country code.", 0, "NONE", None),
        ("bronze.raw_users", "created_at", "TIMESTAMP", "Creation timestamp in postgres.", 0, "NONE", None),
        ("bronze.raw_users", "updated_at", "TIMESTAMP", "Last update timestamp.", 0, "NONE", None),
        
        # bronze.raw_transactions
        ("bronze.raw_transactions", "transaction_id", "TEXT", "Stripe payment identifier.", 0, "NONE", None),
        ("bronze.raw_transactions", "user_id", "TEXT", "Foreign key to user account.", 0, "NONE", None),
        ("bronze.raw_transactions", "amount_usd", "NUMERIC", "Transaction billing value in USD.", 0, "NONE", None),
        ("bronze.raw_transactions", "status", "TEXT", "Payment processor response.", 0, "NONE", None),
        ("bronze.raw_transactions", "payment_method", "TEXT", "Method used: credit card, apple pay, etc.", 0, "NONE", None),
        ("bronze.raw_transactions", "transaction_time", "TIMESTAMP", "Time of charge.", 0, "NONE", None),

        # staging.stg_users
        ("staging.stg_users", "user_id", "TEXT", "Conformed primary customer index.", 0, "NONE", None),
        ("staging.stg_users", "hashed_email", "TEXT", "Hashed secure email identifier for downstream matches.", 1, "EMAIL", "SHA-256 with Pepper Salt"),
        ("staging.stg_users", "masked_phone", "TEXT", "Obfuscated customer contact.", 1, "PHONE", "Masked: keeping code + last 4 digits"),
        ("staging.stg_users", "country", "TEXT", "Standardized uppercase country string.", 0, "NONE", None),
        ("staging.stg_users", "created_timestamp", "TIMESTAMP", "Standardized user creation timestamp.", 0, "NONE", None),
        ("staging.stg_users", "updated_timestamp", "TIMESTAMP", "Standardized profile update timestamp.", 0, "NONE", None),

        # staging.stg_transactions
        ("staging.stg_transactions", "transaction_id", "TEXT", "Standardized primary transaction ID.", 0, "NONE", None),
        ("staging.stg_transactions", "user_id", "TEXT", "Cleaned foreign key reference to user.", 0, "NONE", None),
        ("staging.stg_transactions", "transaction_amount_usd", "DECIMAL(18,2)", "Standardized amount in USD decimal format.", 0, "NONE", None),
        ("staging.stg_transactions", "transaction_status", "TEXT", "Lowercase transaction response code.", 0, "NONE", None),
        ("staging.stg_transactions", "payment_method", "TEXT", "Consolidated billing method.", 0, "NONE", None),
        ("staging.stg_transactions", "transaction_timestamp", "TIMESTAMP", "Standardized charge timestamp.", 0, "NONE", None),

        # marts.fct_user_transactions
        ("marts.fct_user_transactions", "user_id", "TEXT", "Primary index key (one per user).", 0, "NONE", None),
        ("marts.fct_user_transactions", "lifetime_transaction_count", "INTEGER", "Aggregated completed purchases count.", 0, "NONE", None),
        ("marts.fct_user_transactions", "lifetime_spend_usd", "DECIMAL(18,2)", "Aggregated gross user spend in USD.", 0, "NONE", None),
        ("marts.fct_user_transactions", "last_active_timestamp", "TIMESTAMP", "Timestamp of the user's latest completed charge.", 0, "NONE", None),

        # marts.fct_user_churn
        ("marts.fct_user_churn", "user_id", "TEXT", "Primary key for customer analysis.", 0, "NONE", None),
        ("marts.fct_user_churn", "hashed_email", "TEXT", "Anonymized user email for marketing segment hooks.", 1, "EMAIL", "Inherited SHA-256 Mask"),
        ("marts.fct_user_churn", "country", "TEXT", "User registration location.", 0, "NONE", None),
        ("marts.fct_user_churn", "tx_count", "INTEGER", "Total transaction count.", 0, "NONE", None),
        ("marts.fct_user_churn", "spend_amount", "DECIMAL(18,2)", "Total aggregated lifetime spending.", 0, "NONE", None),
        ("marts.fct_user_churn", "last_active_timestamp", "TIMESTAMP", "Most recent activity recorded.", 0, "NONE", None),
        ("marts.fct_user_churn", "churn_status", "TEXT", "Flag: 'ACTIVE' (activity <= 30d ago) or 'CHURNED' (activity > 30d ago).", 0, "NONE", None)
    ]
    cursor.executemany("INSERT INTO columns VALUES (?, ?, ?, ?, ?, ?, ?)", columns)

    # Seeding Lineage
    lineage = [
        ("bronze.raw_users", "staging.stg_users", "Direct"),
        ("bronze.raw_transactions", "staging.stg_transactions", "Direct"),
        ("staging.stg_transactions", "marts.fct_user_transactions", "Aggregated"),
        ("staging.stg_users", "marts.fct_user_churn", "Direct"),
        ("marts.fct_user_transactions", "marts.fct_user_churn", "Direct")
    ]
    cursor.executemany("INSERT INTO lineage VALUES (?, ?, ?)", lineage)

    # Seeding Pipeline SLOs
    slos = [
        ("user_analytics_pipeline", "08:00:00", 3600, 99.0)
    ]
    cursor.executemany("INSERT INTO pipeline_slo VALUES (?, ?, ?, ?)", slos)

    # Seeding Pipeline Runs
    runs = [
        (1001, "user_analytics_pipeline", "SUCCESS", "2026-05-29T02:00:00Z", "2026-05-29T02:00:30Z", 30, None, "mock_data/logs/run_1001_success.log"),
        (1002, "user_analytics_pipeline", "FAILED", "2026-05-30T04:15:00Z", "2026-05-30T04:15:14Z", 14, "Marts unique key violation inside marts.fct_user_churn", "mock_data/logs/run_1002_failed.log"),
        (1003, "user_analytics_pipeline", "FAILED", "2026-05-31T02:00:00Z", "2026-05-31T02:01:02Z", 62, "Database extraction timed out after 3 retries.", "mock_data/logs/run_1003_failed.log")
    ]
    cursor.executemany("INSERT INTO pipeline_runs VALUES (?, ?, ?, ?, ?, ?, ?, ?)", runs)

    conn.commit()
    conn.close()
    print("Created and seeded SQLite metadata database.")

if __name__ == "__main__":
    setup_directories()
    setup_docs()
    setup_codebase()
    setup_logs()
    setup_sqlite()
    print("Mock environment setup successfully!")
